//! Minimal PDF text extraction for bank receipts (VakıfBank's `Dekont.pdf`, generated by Aspose.Words).
//!
//! The receipt is a table; the generator draws every table cell as its own `BT … ET` text block, with the
//! label and the value in separate cells. So there is no layout to reconstruct: the string runs inside one
//! block are concatenated (kerning splits words across runs and fonts), whitespace is collapsed, and each
//! block becomes one "cell". Literal strings are WinAnsi (the Turkish letters come from two CID fonts whose
//! 2-byte glyph ids are mapped through their `ToUnicode` CMaps). Only `FlateDecode` streams are inflated;
//! images are never touched. Everything else in the file is ignored, so a receipt is parsed from the same
//! bytes the DKIM signature covers, with no external fonts or libraries.
use crate::text::find_bytes;
use miniz_oxide::inflate::decompress_to_vec_zlib_with_limit;
use std::collections::BTreeMap;

const MAX_PDF: usize = 4 << 20;
const MAX_INFLATED: usize = 2 << 20;
const MAX_CELLS: usize = 1024;

type CMap = BTreeMap<u32, String>;

struct Obj<'a> {
    num: u32,
    body: &'a [u8],
}

/// All text cells of the first page, in drawing order.
pub fn extract_cells(pdf: &[u8]) -> Result<Vec<String>, String> {
    if pdf.len() > MAX_PDF || !pdf.starts_with(b"%PDF-") {
        return Err("not a PDF or too large".into());
    }
    let objs = objects(pdf);
    let get = |n: u32| objs.iter().find(|o| o.num == n).map(|o| o.body);

    // font resource name → ToUnicode CMap (only Type0/CID fonts have one)
    let mut fonts: BTreeMap<String, Option<CMap>> = BTreeMap::new();
    for o in &objs {
        if let Some(dict) = find_bytes(o.body, b"/Font").and_then(|i| dict_after(&o.body[i + 5..])) {
            for (name, num) in name_refs(dict) {
                let font = match get(num) {
                    Some(f) => f,
                    None => continue,
                };
                let cmap = dict_ref(font, b"/ToUnicode")
                    .and_then(get)
                    .and_then(|c| stream_of(c).ok().and_then(|(_, data)| inflate(data).ok()))
                    .map(|d| parse_cmap(&d));
                fonts.insert(name, cmap);
            }
        }
    }

    // page → content streams
    let page = objs
        .iter()
        .find(|o| (has(o.body, b"/Type /Page") || has(o.body, b"/Type/Page")) && !has(o.body, b"/Type /Pages") && !has(o.body, b"/Type/Pages"))
        .ok_or("no /Page object")?;
    let mut contents: Vec<u32> = Vec::new();
    if let Some(i) = find_bytes(page.body, b"/Contents") {
        let rest = &page.body[i + 9..];
        let rest = skip_ws(rest);
        if rest.starts_with(b"[") {
            let end = find_bytes(rest, b"]").ok_or("bad /Contents array")?;
            contents.extend(refs_in(&rest[1..end]));
        } else if let Some(n) = parse_ref(rest) {
            contents.push(n);
        }
    }
    if contents.is_empty() {
        return Err("page has no /Contents".into());
    }

    let mut cells = Vec::new();
    for n in contents {
        let body = get(n).ok_or("missing content stream")?;
        let (dict, data) = stream_of(body)?;
        let data = if has(dict, b"/FlateDecode") { inflate(data)? } else { data.to_vec() };
        cells_from_content(&data, &fonts, &mut cells)?;
        if cells.len() > MAX_CELLS {
            return Err("too many text cells".into());
        }
    }
    Ok(cells)
}

// ───────────────────────────── objects & streams ─────────────────────────────

fn objects(pdf: &[u8]) -> Vec<Obj<'_>> {
    let mut out = Vec::new();
    let mut pos = 0;
    while let Some(i) = find_bytes(&pdf[pos..], b" 0 obj") {
        let at = pos + i;
        // walk back over the object number
        let mut s = at;
        while s > 0 && pdf[s - 1].is_ascii_digit() {
            s -= 1;
        }
        let num = std::str::from_utf8(&pdf[s..at]).ok().and_then(|t| t.parse::<u32>().ok());
        let start = at + 6;
        let end = find_bytes(&pdf[start..], b"endobj").map(|e| start + e).unwrap_or(pdf.len());
        if let Some(num) = num {
            if s == 0 || !pdf[s - 1].is_ascii_digit() {
                out.push(Obj { num, body: &pdf[start..end] });
            }
        }
        pos = end.max(at + 6);
    }
    out
}

/// (dictionary bytes, raw stream bytes) of an object with a stream.
fn stream_of(body: &[u8]) -> Result<(&[u8], &[u8]), String> {
    let i = find_bytes(body, b"stream").ok_or("no stream")?;
    let dict = &body[..i];
    let mut start = i + 6;
    if body[start..].starts_with(b"\r\n") {
        start += 2;
    } else if body[start..].starts_with(b"\n") {
        start += 1;
    }
    // prefer the declared /Length when it is a direct integer and lands on "endstream"
    if let Some(len) = dict_int(dict, b"/Length") {
        let end = start + len;
        if end <= body.len() && find_bytes(&body[end..(end + 12).min(body.len())], b"endstream").is_some() {
            return Ok((dict, &body[start..end]));
        }
    }
    let e = find_bytes(&body[start..], b"endstream").ok_or("no endstream")?;
    let mut end = start + e;
    while end > start && (body[end - 1] == b'\n' || body[end - 1] == b'\r') {
        end -= 1;
    }
    Ok((dict, &body[start..end]))
}

fn inflate(data: &[u8]) -> Result<Vec<u8>, String> {
    decompress_to_vec_zlib_with_limit(data, MAX_INFLATED).map_err(|e| format!("inflate: {e:?}"))
}

fn has(hay: &[u8], needle: &[u8]) -> bool {
    find_bytes(hay, needle).is_some()
}

fn skip_ws(b: &[u8]) -> &[u8] {
    let mut i = 0;
    while i < b.len() && b[i].is_ascii_whitespace() {
        i += 1;
    }
    &b[i..]
}

/// `/Key 12 0 R` → 12
fn dict_ref(dict: &[u8], key: &[u8]) -> Option<u32> {
    let i = find_bytes(dict, key)?;
    parse_ref(skip_ws(&dict[i + key.len()..]))
}

fn parse_ref(b: &[u8]) -> Option<u32> {
    let (n, rest) = parse_uint(b)?;
    let rest = skip_ws(rest);
    let (g, rest) = parse_uint(rest)?;
    let rest = skip_ws(rest);
    (g == 0 && rest.starts_with(b"R")).then_some(n)
}

fn parse_uint(b: &[u8]) -> Option<(u32, &[u8])> {
    let mut i = 0;
    let mut v: u32 = 0;
    while i < b.len() && b[i].is_ascii_digit() {
        v = v.checked_mul(10)?.checked_add((b[i] - b'0') as u32)?;
        i += 1;
    }
    (i > 0).then_some((v, &b[i..]))
}

fn dict_int(dict: &[u8], key: &[u8]) -> Option<usize> {
    let i = find_bytes(dict, key)?;
    let rest = skip_ws(&dict[i + key.len()..]);
    let (n, rest) = parse_uint(rest)?;
    // "/Length 12 0 R" is an indirect length: not supported here, fall back to searching
    (!skip_ws(rest).starts_with(b"0 R")).then_some(n as usize)
}

/// The `<< … >>` following a key (one level of nesting).
fn dict_after(b: &[u8]) -> Option<&[u8]> {
    let b = skip_ws(b);
    if !b.starts_with(b"<<") {
        return None;
    }
    let mut depth = 0i32;
    let mut i = 0;
    while i + 1 < b.len() {
        if &b[i..i + 2] == b"<<" {
            depth += 1;
            i += 2;
        } else if &b[i..i + 2] == b">>" {
            depth -= 1;
            i += 2;
            if depth == 0 {
                return Some(&b[2..i - 2]);
            }
        } else {
            i += 1;
        }
    }
    None
}

/// `/Name 12 0 R` pairs inside a dictionary.
fn name_refs(dict: &[u8]) -> Vec<(String, u32)> {
    let mut out = Vec::new();
    let mut i = 0;
    while i < dict.len() {
        if dict[i] == b'/' {
            let mut j = i + 1;
            while j < dict.len() && !dict[j].is_ascii_whitespace() && !b"/<>[]()".contains(&dict[j]) {
                j += 1;
            }
            let name = String::from_utf8_lossy(&dict[i + 1..j]).into_owned();
            if let Some(n) = parse_ref(skip_ws(&dict[j..])) {
                out.push((name, n));
            }
            i = j;
        } else {
            i += 1;
        }
    }
    out
}

fn refs_in(b: &[u8]) -> Vec<u32> {
    let mut out = Vec::new();
    let mut rest = skip_ws(b);
    while let Some(n) = parse_ref(rest) {
        out.push(n);
        // advance past "n 0 R"
        let mut k = 0;
        let mut seen_r = false;
        while k < rest.len() && !seen_r {
            seen_r = rest[k] == b'R';
            k += 1;
        }
        rest = skip_ws(&rest[k..]);
    }
    out
}

// ───────────────────────────── ToUnicode ─────────────────────────────

fn parse_cmap(d: &[u8]) -> CMap {
    let mut map = CMap::new();
    let mut pos = 0;
    while let Some(i) = find_bytes(&d[pos..], b"beginbf") {
        let at = pos + i;
        let is_range = d[at..].starts_with(b"beginbfrange");
        let kw_len = if is_range { 12 } else { 11 };
        let end_kw: &[u8] = if is_range { b"endbfrange" } else { b"endbfchar" };
        let body_start = at + kw_len;
        let body_end = find_bytes(&d[body_start..], end_kw).map(|e| body_start + e).unwrap_or(d.len());
        let hexes = hex_tokens(&d[body_start..body_end]);
        if is_range {
            for tri in hexes.chunks(3) {
                if let [lo, hi, dst] = tri {
                    let (lo, hi) = (hex_u32(lo), hex_u32(hi));
                    if hi < lo || hi - lo > 65535 {
                        continue;
                    }
                    let base = utf16_hex(dst);
                    let last = base.chars().last().map(|c| c as u32).unwrap_or(0);
                    for c in lo..=hi {
                        let ch = char::from_u32(last + (c - lo)).unwrap_or('?');
                        map.insert(c, ch.to_string());
                    }
                }
            }
        } else {
            for pair in hexes.chunks(2) {
                if let [src, dst] = pair {
                    map.insert(hex_u32(src), utf16_hex(dst));
                }
            }
        }
        pos = body_end;
    }
    map
}

fn hex_tokens(b: &[u8]) -> Vec<&[u8]> {
    let mut out = Vec::new();
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'<' {
            let j = find_bytes(&b[i..], b">").map(|e| i + e).unwrap_or(b.len());
            out.push(&b[i + 1..j]);
            i = j + 1;
        } else {
            i += 1;
        }
    }
    out
}

fn hex_u32(h: &[u8]) -> u32 {
    h.iter().filter(|c| c.is_ascii_hexdigit()).fold(0u32, |v, c| (v << 4) | (*c as char).to_digit(16).unwrap_or(0)) & 0xFFFF_FFFF
}

fn hex_bytes(h: &[u8]) -> Vec<u8> {
    let digits: Vec<u8> = h.iter().filter(|c| c.is_ascii_hexdigit()).map(|c| (*c as char).to_digit(16).unwrap_or(0) as u8).collect();
    digits.chunks(2).map(|p| (p[0] << 4) | p.get(1).copied().unwrap_or(0)).collect()
}

fn utf16_hex(h: &[u8]) -> String {
    let bytes = hex_bytes(h);
    let units: Vec<u16> = bytes.chunks(2).map(|p| ((p[0] as u16) << 8) | p.get(1).copied().unwrap_or(0) as u16).collect();
    char::decode_utf16(units).map(|r| r.unwrap_or('?')).collect()
}

// ───────────────────────────── content stream ─────────────────────────────

fn cells_from_content(c: &[u8], fonts: &BTreeMap<String, Option<CMap>>, cells: &mut Vec<String>) -> Result<(), String> {
    let mut i = 0;
    let mut in_text = false;
    let mut buf = String::new();
    let mut last_name: Option<String> = None;
    let mut last_num: f64 = 0.0;
    let mut cmap: Option<&CMap> = None;
    while i < c.len() {
        let b = c[i];
        match b {
            b'%' => {
                while i < c.len() && c[i] != b'\n' && c[i] != b'\r' {
                    i += 1;
                }
            }
            b'(' => {
                let (bytes, next) = literal_string(c, i)?;
                if in_text {
                    push_bytes(&mut buf, &bytes, cmap);
                }
                i = next;
            }
            b'<' if c.get(i + 1) != Some(&b'<') => {
                let j = find_bytes(&c[i..], b">").map(|e| i + e).ok_or("unterminated hex string")?;
                if in_text {
                    push_bytes(&mut buf, &hex_bytes(&c[i + 1..j]), cmap);
                }
                i = j + 1;
            }
            b'<' => i += 2, // "<<" dictionary (marked content); its contents are lexed like everything else
            b'/' => {
                let mut j = i + 1;
                while j < c.len() && !c[j].is_ascii_whitespace() && !b"/<>[]()".contains(&c[j]) {
                    j += 1;
                }
                last_name = Some(String::from_utf8_lossy(&c[i + 1..j]).into_owned());
                i = j;
            }
            b'-' | b'+' | b'.' | b'0'..=b'9' => {
                let mut j = i + 1;
                while j < c.len() && (c[j].is_ascii_digit() || c[j] == b'.') {
                    j += 1;
                }
                last_num = std::str::from_utf8(&c[i..j]).ok().and_then(|t| t.parse().ok()).unwrap_or(0.0);
                // inside a TJ array a large negative adjustment is a word gap for generators that omit spaces
                if in_text && last_num <= -200.0 && !buf.ends_with(' ') {
                    buf.push(' ');
                }
                i = j;
            }
            b'a'..=b'z' | b'A'..=b'Z' | b'\'' | b'"' | b'*' => {
                let mut j = i + 1;
                while j < c.len() && (c[j].is_ascii_alphanumeric() || c[j] == b'*' || c[j] == b'\'' || c[j] == b'"') {
                    j += 1;
                }
                match &c[i..j] {
                    b"BT" => {
                        in_text = true;
                        buf.clear();
                    }
                    b"ET" => {
                        in_text = false;
                        let cell: String = buf.split_whitespace().collect::<Vec<_>>().join(" ");
                        if !cell.is_empty() {
                            cells.push(cell);
                        }
                        buf.clear();
                    }
                    b"Tf" => {
                        cmap = last_name.as_ref().and_then(|n| fonts.get(n)).and_then(|c| c.as_ref());
                    }
                    b"BI" => return Err("inline images are not supported".into()),
                    _ => {}
                }
                i = j;
            }
            _ => i += 1,
        }
    }
    Ok(())
}

/// Parse a `( … )` literal string starting at `c[i]`; returns (bytes, index after the closing paren).
fn literal_string(c: &[u8], i: usize) -> Result<(Vec<u8>, usize), String> {
    let mut out = Vec::new();
    let mut depth = 1;
    let mut j = i + 1;
    while j < c.len() {
        match c[j] {
            b'\\' => {
                j += 1;
                let e = *c.get(j).ok_or("unterminated string")?;
                match e {
                    b'n' => out.push(b'\n'),
                    b'r' => out.push(b'\r'),
                    b't' => out.push(b'\t'),
                    b'b' => out.push(8),
                    b'f' => out.push(12),
                    b'\n' => {}
                    b'\r' => {
                        if c.get(j + 1) == Some(&b'\n') {
                            j += 1;
                        }
                    }
                    b'0'..=b'7' => {
                        let mut v: u32 = 0;
                        let mut k = 0;
                        while k < 3 && j < c.len() && (b'0'..=b'7').contains(&c[j]) {
                            v = v * 8 + (c[j] - b'0') as u32;
                            j += 1;
                            k += 1;
                        }
                        out.push((v & 0xFF) as u8);
                        continue;
                    }
                    other => out.push(other),
                }
                j += 1;
            }
            b'(' => {
                depth += 1;
                out.push(b'(');
                j += 1;
            }
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Ok((out, j + 1));
                }
                out.push(b')');
                j += 1;
            }
            other => {
                out.push(other);
                j += 1;
            }
        }
    }
    Err("unterminated string".into())
}

/// Append decoded text: 2-byte CIDs through the font's CMap, else WinAnsi single bytes.
fn push_bytes(buf: &mut String, bytes: &[u8], cmap: Option<&CMap>) {
    match cmap {
        Some(m) => {
            for p in bytes.chunks(2) {
                let cid = ((p[0] as u32) << 8) | p.get(1).copied().unwrap_or(0) as u32;
                match m.get(&cid) {
                    Some(s) => buf.push_str(s),
                    None => buf.push('?'),
                }
            }
        }
        None => {
            for &b in bytes {
                buf.push(winansi(b));
            }
        }
    }
}

fn winansi(b: u8) -> char {
    match b {
        0x80 => '€',
        0x8A => 'Š',
        0x8C => 'Œ',
        0x8E => 'Ž',
        0x9A => 'š',
        0x9C => 'œ',
        0x9E => 'ž',
        0x9F => 'Ÿ',
        0x81..=0x9F => '?',
        _ => b as char, // ASCII and Latin-1 (CP1252 agrees with Latin-1 from 0xA0 up)
    }
}
